name: flutter_internship_submission
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_core_platform_interface: 4.5.1
  geolocator: ^8.0.3
  firebase_storage: ^10.2.7
  cached_network_image: ^3.2.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  sn_progress_dialog: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/

